name = "QSMC Template"
author = "<name here>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e80513f459d508b53bba4ac1f1dd4792a021d79fb2c2fcb4de1ce0d12d6084cd"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
